Feat/#508 sidebar time
ever-co/ever-teams pull request #1047
Opened 2023-07-20 14:40 UTC by desperado1802

Added functionality to the task sidebar progress section

- Fixed progressbar bug, When task with estimation was running, and we enter another task without estimation's page, the another task was showing previous task's estimation in progress bar
- Displayed current user work time
- Displayed current user work time for the day on task
- Total group time
- When dropdown clicked shows each member how much time worked on task(if task's member count is less than 2 the dropdown is not rendered)
- Added Show More button. Initially 5 members are rendered in dropdown, if there are more Show Button renders, and once pressed renders 5 more members
- Time remaining, shows estimate time minus the total worked time

For DEMONSTRATION purpose in the video one member is rendered each time when Show More is pressed. Normally 5 members will be rendered
https://github.com/ever-co/ever-teams/assets/124465103/80dfa027-5058-42f4-9990-ec473fc566a5

2023-07-20 16:27 UTC, evereq commented
https://capture.dropbox.com/pOUqk1xz0sljc3F4 @desperado1802 :)

2023-07-20 16:29 UTC, evereq commented
oh haha, sorry I did not read carefully description :))) Now I see you saying it's for DEMO you did it like that :D OK, 5 members with SHOW MORE is good choice, thanks and sorry for confusion @desperado1802 :) 

@Babajide777 can you review this one please and if all good, I will merge code?

2023-07-20 17:19 UTC, badalkhatri0924 commented
@desperado1802 Plz check this negative Time Remaining.

I've done this: Assigned a task to 2 users and estimated 2 minutes for the task, started timer from both the users and after 2 minutes it is showing negative values.

<img width="411" alt="image" src="https://github.com/ever-co/ever-teams/assets/81486442/e231ebaa-dd05-406a-9334-d59f83522056">
<img width="407" alt="image" src="https://github.com/ever-co/ever-teams/assets/81486442/f4c73d20-53b5-4632-ad86-da5bc13437a9">

2023-07-20 17:46 UTC, badalkhatri0924 requested changes

2023-07-20 17:46 UTC, badalkhatri0924 commented on apps/web/components/pages/task/details-section/blocks/task-progress.tsx
> +import { ITasksTimesheet } from '@app/interfaces/ITimer';
@desperado1802 Let's import it from `@app/interfaces`. If it is not present in `index.ts` file plz add it.

2023-07-20 17:46 UTC, badalkhatri0924 commented on apps/web/components/pages/task/details-section/blocks/task-progress.tsx
> +interface ITime {
@desperado1802 Plz add this interface in `ITimer.ts`, we will reuse it from there.

2023-07-20 17:46 UTC, badalkhatri0924 commented on apps/web/components/pages/task/details-section/blocks/task-progress.tsx
> +		console.log('matchingMembers:', matchingMembers);
@desperado1802 let's remove this console, and any other consoles that we by mistake forgot to remove!

2023-07-20 17:46 UTC, badalkhatri0924 commented on apps/web/components/pages/task/details-section/blocks/task-progress.tsx
> +							{task?.members !== undefined && task?.members.length > 1 ? (
Insted of `task?.members !== undefined && task?.members.length > 1` we can use `task?.members && task?.members.length`

2023-07-20 17:46 UTC, badalkhatri0924 commented on apps/web/components/pages/task/details-section/blocks/task-progress.tsx
> +							{task?.members !== undefined && task?.members.length > 1 && (
Update this condiction as above too.

2023-07-21 11:03 UTC, desperado1802 commented
> @desperado1802 Plz check this negative Time Remaining.
> 
> I've done this: Assigned a task to 2 users and estimated 2 minutes for the task, started timer from both the users and after 2 minutes it is showing negative values.
> 
> <img alt="image" width="411" src="https://user-images.githubusercontent.com/81486442/254958986-e231ebaa-dd05-406a-9334-d59f83522056.png"> <img alt="image" width="407" src="https://user-images.githubusercontent.com/81486442/254959345-f4c73d20-53b5-4632-ad86-da5bc13437a9.png"> <img alt="image" width="1420" src="https://user-images.githubusercontent.com/81486442/254961006-76f64748-854f-4980-af81-a67cd2544679.png">

Fixed the negative time remainig when timer hits 0 and bellow. 
![image](https://github.com/ever-co/ever-teams/assets/124465103/0eda537b-7a58-4308-b25b-92ed35fde99c)

2023-07-21 11:51 UTC, badalkhatri0924 requested changes

2023-07-21 11:51 UTC, badalkhatri0924 commented on apps/web/components/pages/task/details-section/blocks/task-progress.tsx
> +		const userTotalTimeOnTaskToday = (): void => {
@desperado1802 We can use useCallback hook for `userTotalTimeOnTask` and `userTotalTimeOnTaskToday`, then we can call that in useEffect

2023-07-21 12:17 UTC, badalkhatri0924 commented
@evereq we can merge this now.

2023-07-21 12:17 UTC, badalkhatri0924 approved these changes

2023-07-21 12:33 UTC, merged