Bug/task type badge UI
ever-co/ever-teams pull request #1223
Opened 2023-08-10 16:15 UTC by desperado1802

![image](https://github.com/ever-co/ever-teams/assets/124465103/3b3fb84e-ec81-4d24-b60d-85d20ab509c1)
![image](https://github.com/ever-co/ever-teams/assets/124465103/3cece031-1efe-4bcb-b693-158894c8a5ad)
![image](https://github.com/ever-co/ever-teams/assets/124465103/e98274ad-6f07-41a4-bd8a-59cb7d74219c)

2023-08-10 16:19 UTC, badalkhatri0924 commented
<img width="1440" alt="image" src="https://github.com/ever-co/ever-teams/assets/81486442/2b706b4a-c563-4cd9-b3bf-7ca274187de1">
@desperado1802 Badge missing may be only in large title (mostly there will be large title only), so check with multiple length titls

2023-08-10 16:25 UTC, badalkhatri0924 commented
### Our implementation
<img width="159" alt="image" src="https://github.com/ever-co/ever-teams/assets/81486442/85b6a2e5-3c9d-4cc2-91cb-0fd8c31991d4">

### Expected
<img width="124" alt="image" src="https://github.com/ever-co/ever-teams/assets/81486442/512e480f-f57f-41ce-a8cf-b504eead3b1d">

@desperado1802

2023-08-10 23:09 UTC, desperado1802 commented
Now the long title doesn't make the badge to disappear:
![image](https://github.com/ever-co/ever-teams/assets/124465103/cdaa301a-3c9f-40ce-8619-a73b8fc40dc1)

Fixed the child tasks ui also:
![Uploading image.png…]()

2023-08-11 02:39 UTC, badalkhatri0924 commented
### Current implementation
<img width="1438" alt="image" src="https://github.com/ever-co/ever-teams/assets/81486442/93274fc8-ae14-4eef-8d15-5a3411a22ab3">


### Expected
<img width="924" alt="image" src="https://github.com/ever-co/ever-teams/assets/81486442/b38d5654-b300-473f-b302-f3cc44814c4f">


@desperado1802 Plz check each and every screen in Figma and compare with out screens, wherever require do the changes.

2023-08-11 09:45 UTC, badalkhatri0924 requested changes

2023-08-11 09:45 UTC, badalkhatri0924 commented on apps/web/components/pages/task/details-section/blocks/task-estimations-info.tsx
> +						<div className="flex flex-col w-full mt-[0.1875rem]">
<img width="527" alt="image" src="https://github.com/ever-co/ever-teams/assets/81486442/e3c6abf7-99a9-4992-9897-f4f01d7e917b">

@desperado1802 this is still not properly centered.

2023-08-11 09:45 UTC, badalkhatri0924 commented on apps/web/components/pages/task/details-section/blocks/task-progress.tsx
> +						<div className="flex flex-col w-full mt-[0.1875rem]">
<img width="436" alt="image" src="https://github.com/ever-co/ever-teams/assets/81486442/d8973d75-8521-47c8-8244-39e4ec041cd3">

this is also not centered properly

2023-08-12 03:02 UTC, badalkhatri0924 approved these changes

2023-08-12 06:53 UTC, merged