Feat/Related Task Issue
ever-co/ever-teams pull request #1270
Opened 2023-08-16 10:13 UTC by paradoxe35

2023-08-16 15:09 UTC, evereq commented
@Babajide777 can you review as priority please so we merge?

2023-08-16 15:10 UTC, evereq commented
One notice: in the screenshot, we can see that status "In Progress" did not fit, let's make those fields bigger so status "IN PROGRESS" can fit into them. @paradoxe35 
CC: @Babajide777

2023-08-16 15:28 UTC, evereq commented
@paradoxe35 yes, but for so important things as Status for the task, i would really prefer to make the combobox bigger width so it fits that specific common status "IN PROGRESS", especially as we see there is tons of empty space there... We don't need to make it much longer, just a bit more than now and it will fit text well!

2023-08-16 15:33 UTC, paradoxe35 commented
You're right @evereq 

@badalkhatri0924  let's create a separate PR for this, if you agree

2023-08-16 16:43 UTC, badalkhatri0924 commented
> You're right @evereq
> 
> @badalkhatri0924 let's create a separate PR for this, if you agree

Yes lets do it in separate PR.

2023-08-16 16:59 UTC, badalkhatri0924 requested changes

2023-08-16 16:59 UTC, badalkhatri0924 commented on apps/web/components/pages/task/IssueCard.tsx
> +			!['Epic', 'Story'].includes(t.issueType)
@paradoxe35 this logic is breaking. Please refactor it.

If current task is EPIC then STORY, TASK, BUG can be children
If current task is  STORY then TASK, BUG can be children
If current task is TASK|BUG then both can be children.

2023-08-16 16:59 UTC, badalkhatri0924 commented on apps/web/components/pages/task/IssueCard.tsx
>  			task?.linkedIssues
@paradoxe35 can you try to improve this logic? multiple .filter and .map will reduce the performance when we have more tasks.

2023-08-16 16:59 UTC, badalkhatri0924 commented on apps/web/components/pages/task/ChildIssueCard.tsx
> +			<div className="w-[98%] md:w-[668px] relative">
@paradoxe35 can we use `rem` instead of `px` here? Lets shift to `rem` in whole projects gradually for old code. and new code we use rem only.

2023-08-16 17:03 UTC, badalkhatri0924 commented
<img width="1081" alt="image" src="https://github.com/ever-co/ever-teams/assets/81486442/076b1f58-f4a6-4350-927e-cc452b2e2db1">

@paradoxe35 plz update the divider the same as we have at other places. the white divider is not looking good.

2023-08-17 00:43 UTC, badalkhatri0924 approved these changes

2023-08-17 06:49 UTC, merged