Feat/ Remove Invitation Mobile
ever-co/ever-teams pull request #1358
Opened 2023-09-12 12:45 UTC by desperado1802

#1356
Added functionality for invitation to be removed
https://github.com/ever-co/ever-teams/assets/124465103/c52b0aa1-fb37-4a47-abe1-bec946b7ce95

2023-09-12 16:47 UTC, badalkhatri0924 requested changes

2023-09-12 16:47 UTC, badalkhatri0924 commented on apps/mobile/app/services/hooks/useTeamInvitation.ts
> +		}).catch((err) => console.log(err))
@desperado1802 Lets avoid console logs in mobile appliation.

2023-09-12 16:47 UTC, badalkhatri0924 commented on apps/mobile/app/services/hooks/useTeamInvitation.ts
> +		await removeTeamInvitationsRequest({
@desperado1802 can we remove the card at the same time user remove the invite, updating local state and then do API call to remove?

We want to make the app very responsive. Even we will be doing that in web too gradually.

2023-09-12 17:15 UTC, badalkhatri0924 requested changes

2023-09-12 17:15 UTC, badalkhatri0924 commented on apps/mobile/app/screens/Authenticated/TeamScreen/components/InviteCardItem.tsx
> +								<ListItem
@desperado1802 let's take user confirmation too.

<img width="320" alt="image" src="https://github.com/ever-co/ever-teams/assets/81486442/df881980-638d-445e-88e8-5dad626d5c99">

2023-09-13 08:38 UTC, desperado1802 commented on apps/mobile/app/screens/Authenticated/TeamScreen/components/InviteCardItem.tsx
> +								<ListItem
https://github.com/ever-co/ever-teams/assets/124465103/4ad9c64f-5f0c-4fc6-a199-cf247f57e608

2023-09-13 13:43 UTC, badalkhatri0924 approved these changes

2023-09-13 15:00 UTC, merged